base_url = "https://voidwalter.github.io"
title = "Walter"
description = "Walter's blog page"
default_language = "en"
theme = "zerene"
output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false
github_alerts = true

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "archives", path = "/archives", is_external = false },
  # { name = "notes", path = "/notes", is_external = false },
  { name = "bookmark", path = "/bookmark", is_external = false},
  { name = "lists", path = "/normie", is_external = false},
  { name = "about", path = "/about", is_external = false },
  # { name = "tags", path = "/tags", is_external = false },
]

blog_section_path = "/archives"
back_link_text = "Back" # Text of the back button
force_theme = "dark"
footer_copyright = "© 2026 Walter"
footer_credits = false
not_found_error_text = "this derivation does not exist"
not_found_recover_text = "« rollback »"

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
