[[collection]]
type = "art"
title = "Any Spider-Man Movies"
subtitle = "My first time watching a movie was Spider-Man. It was Spider-Man: Into The Spider Verse (Cause, I know nothing about Spider-Man this time). Apparently, I've seen many good movies, But I just want to keep it on top. Most favorite: Spider-Man: Homecoming(6 times) > Spider-Man 2 (4 times) > The Amazing Spider-Man (both) "
img = "https://i.pinimg.com/originals/c8/7b/b4/c87bb4f13f03cb64815435215495204a.jpg"

[[collection]]
type = "art"
title = "Spies In Disguise "
subtitle = "Second favorite movie. Mostly for Nerdy Walter Beckett. It had a good story and even better characters. Also, because of, I love watching Tom Holland's movies."
img = "https://image.tmdb.org/t/p/original/z52xI0MnoX1rqySFJYnmBqHbXRn.jpg"
