[[collection]]
type = "art_simple"
img = "https://static1.cbrimages.com/wordpress/wp-content/uploads/sharedimages/2024/09/dr-stone-2019.jpg"
title = "Dr. Stone"

[[collection]]
type = "art_simple"
img = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/sharedimages/2024/04/chainsaw-man-anime-poster.jpg"
title = "Chainsaw Man"

[[collection]]
type = "art_simple"
img = "https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/09/death-note.jpg"
title = "Death Note"

[[collection]]
type = "art_simple"
img = "https://static1.cbrimages.com/wordpress/wp-content/uploads/sharedimages/2024/07/dragon-ball-1986.jpg"
title = "Dragon Ball"
