[[collection]]
type = "art_simple"
img = "https://www.hachette.com.au/content/books/9781975382605.jpg"
title = "Penguin Highway"

[[collection]]
type = "art_simple"
img = "https://i.pinimg.com/originals/6e/f5/b0/6ef5b05f749a7230c41cfd47fa231750.jpg"
title = "I Want to Eat Your Pancreas"

[[collection]]
type = "art_simple"
img = "https://i.pinimg.com/originals/f3/fa/ad/f3faad5c1f6608031f188572e502b007.jpg"
title = "A Silent Voice"
