[[collection]]
type = "entry"
title = "Why I don't have fun with Claude-Code"
subtitle = "Stephen Brennan"
link = "https://brennan.io/2026/01/23/claude-code/"

[[collection]]
type = "entry"
title = "I am Not Convinced by Vibe Coding"
subtitle = "notashelf"
link = "https://notashelf.dev/posts/vibe-coding"

[[collection]]
type = "entry"
title = "How to work full-time without a salary, aka do FOSS."
subtitle = "vaxry"
link = "https://blog.vaxry.net/articles/2023-workingFullTime"

[[collection]]
type = "entry"
title = "Modern Freedom Means Being a Slave to Impulses"
subtitle = "Luke Smith"
link = "https://lukesmith.xyz/articles/modern-freedom-means-being-a-slave-to-impulses/"

[[collection]]
type = "entry"
title = "Write Code Every Day"
subtitle = "John Resig"
link = "https://johnresig.com/blog/write-code-every-day/"

[[collection]]
type = "entry"
title = "Science of The Gaps"
subtitle = "Luke Smith"
link = "https://lukesmith.xyz/articles/science-of-the-gaps/"
